version: "3"
services:
  php80:
    build: "."
    image: "php:8.0-apache"
    ports:
      - "8888:8888"
      #- '443:443'
    volumes:
      - "/var/www:/var/www"
      - "./apache2.conf:/etc/apache2/apache2.conf"
      - "./sites-available:/etc/apache2/sites-available"
      - "./sites-enabled:/etc/apache2/sites-enabled"
      - "./vhost.conf:/etc/apache2/sites-available/000-default.conf"
      - "./ports.conf:/etc/apache2/ports.conf"
      - "./security.conf:/etc/apache2/conf-available/security.conf"
      - "./php.ini:/usr/local/etc/php/php.ini"
      - "./evasive.conf:/etc/apache2/mods-enabled/evasive.conf"
      - "./mpm_worker.conf:/etc/apache2/mods-available/mpm_worker.conf"
      - "./mpm_prefork.conf:/etc/apache2/mods-available/mpm_prefork.conf"
      - "/etc/hosts:/etc/hosts"
      # - "/etc/letsencrypt:/etc/letsencrypt"
      # - '/etc/letsencrypt/options-ssl-apache.conf:/etc/letsencrypt/options-ssl-apache.conf'
      # - '/etc/letsencrypt/live/<dominio>:/etc/letsencrypt/live/httpd'
      # - '/etc/letsencrypt/archive/<dominio>:/etc/letsencrypt/archive/<dominio>'
    restart: "always"
    #networks:
    #  default:
    #    ipv4_address: 10.0.0.255

networks:
  default:
    external:
      name: php-apache
